#!/usr/bin/env bash

if [ $# -gt 0 ]; then
    if [ "$1" == "start" ]; then
        docker-compose up -d
    elif [ "$1" == "stop" ]; then
        docker-compose down
    elif [ "$1" == "composer" ]; then
        shift 1
        docker-compose exec app composer "$@"
    elif [ "$1" == "test" ] || [ "$1" == "phpunit" ]; then
        shift 1
        docker-compose exec app phpunit "$@"
    elif [ "$1" == "yarn" ]; then
        shift 1
        docker-compose run --rm node yarn "%@"
    else
        docker-compose "$@"
    fi
else
    docker-compose ps
fi

