version: '3'
services:
    app:
        build:
            context: ./docker/app
            dockerfile: ./Dockerfile
        image: jarlskov-docker/app:latest
        networks:
            - appnet
        volumes:
            - ./${APP_DIR}:/var/www/html
        ports:
            - ${APP_PORT}:80
        working_dir: /var/www/html
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpassword
        networks:
            - appnet
        volumes:
            - dbdata:/var/lib/mysql
    node:
        build:
            context: ./docker/node
            dockerfile: ./Dockerfile
        image: jarlskov-docker/node
        networks:
            - appnet
        volumes:
            - ./:/opt
        working_dir: /opt
        command: ''
networks:
    appnet:
        driver: bridge
volumes:
    dbdata:
        driver: local
